version: "3.7"

services:
  bdd:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bdd
    ports:
      - 3306:3306
  backend:
    build: demo-cloud/.
    ports:
      - 8080:8080
  
  frontend:
    build: react-front-cloud/.
    ports:
    - 80:80